import { TOKEN_TYPE_ENUM } from "../interfaces";
import { NETWORKS_ADVANCED_ERC20 } from "./ADVANCED/contract.advanced.instance";
import { NETWORKS_STANDARD_ERC20 } from "./STANDARD/standard.contract.instance";
import { NETWORKS_ERC20 } from "./BASIC/contract.basic.instance";
import { NETWORKS_SIMPLE_ERC20 } from "./SIMPLE/contract.simple.instance";
import { ACTIVE_NETWORK_STAKING_TESTNET } from "../../../settings/global";
import { CORE_INSTANCE, BSC_INSTANCE, POLYGON_INSTANCE, BASE_ETH_INSTANCE, CORE_TESTNET_INSTANCE, SONEIUM_INSTANCE, GENESYS_INSTANCE } from "../../../settings/config/network.instances";

export const LIST_NETWORKS_ERC20 = {
  [TOKEN_TYPE_ENUM.SIMPLE]: NETWORKS_SIMPLE_ERC20,
  [TOKEN_TYPE_ENUM.BASIC]: NETWORKS_ERC20,
  [TOKEN_TYPE_ENUM.STANDARD]: NETWORKS_STANDARD_ERC20,
  [TOKEN_TYPE_ENUM.ADVANCED]: NETWORKS_ADVANCED_ERC20,
}


export const GLOBAL_NETWORKS = [
  BSC_INSTANCE,
  POLYGON_INSTANCE,
  CORE_INSTANCE,
  BASE_ETH_INSTANCE,
  SONEIUM_INSTANCE,
  GENESYS_INSTANCE,
  ...(ACTIVE_NETWORK_STAKING_TESTNET ? [CORE_TESTNET_INSTANCE] : [])
]