export const GECKO_PRICES_LIST_KEY = 'GECKO_PRICES_LIST_KEY'
export const GECKO_POOL_KEY = 'GECKO_POOL_KEY'
export const GECKO_TOKEN_KEY = 'GECKO_TOKEN_KEY'
export const GECKO_TOKEN_INFO_KEY = 'GECKO_TOKEN_INFO_KEY'